dependencies:
  - pip:
      - pypdf==5.4.0
      - langchain-openai==0.3.12
      - tenacity==9.1.2
      - langchain==0.3.22
      - langchain-community==0.3.20
      - azure-kusto-data==5.0.2
      - httpx==0.28.1
      - dbutils==3.1.0
      - pdfplumber==0.11.5
      - openai==1.68.2
      - pypdf2==3.0.1
      - chromedriver-autoinstaller==0.6.4
      - selenium==4.29.0
